name = "simple-backend"
compatibility_date = "2024-12-30"
assets = { directory = "./public/" } 

main = "src/index.ts"
workers_dev = true

[[routes]]
pattern = "https://api.pasts.dev/*"
zone_id = "88871c370847b4273ad055bbd9752c18"

[vars]
JWT_SECRET = "your-secret-key-change-this-in-production"
ACCESS_TOKEN_EXPIRES = "1800"  # 30 minutes in seconds
REFRESH_TOKEN_EXPIRES = "2592000"  # 30 days in seconds

[[kv_namespaces]]
binding = "API_KEYS"
id = "24b5458920ef434c96759ea5490211c4"
preview_id = "1407d474e65045d298e75bebeb68dea0"

[observability.logs]
enabled = true  # default: false
